# Generated by Django 4.2.6 on 2023-10-17 14:38

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to=post.models.post_image_file_path),
        ),
    ]
